### ISSUE TITLE
Expose trace IDs in cloud event functions

### ISSUE THREAD

**Issue by juliehockett** [GoogleCloudPlatform/functions-framework-ruby#55]
The `X-Cloud-Trace-Context` header is included in requests, but as we don't expose headers to the event-style functions it is inaccessible. This value is the only means of grouping StackDriver logs by request, and so we should expose it to the user function code.

CloudEvents: The trace ID should be encoded as an extension on the event, leveraging the `traceparent` extension field as described in https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md.

**Comment by dazuma** [comment]
I'm going to close this for now, until there's a specific requirement in the functions framework contract. It also sounds like there's CloudEvents discussion regarding whether even to have the trace context extension at all, due to the confusion it causes between application-level and transport-level tracing.
